 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
 /Users/WRShoemaker/github/Task2/LTDE/analysis
