---
title: "Bacillus dispersion"
author: "William R. Shoemaker, Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
---


```{r}
rm(list=ls())
getwd()
setwd("~/GitHub/Task2/PoolPopSeq")

# Load dependencies
require("vegan")
require("png")
require("grid")
library("scales")

# Source code functions
source("R/ParEvol.R")
```


import data

```{r}
# pop-by-gene matrix
pop_by_gene <- c("data/gene_by_sample/B_S/sample_by_gene.txt")
df <- read.table(paste(pop_by_gene, collapse = ''), sep = "\t", header = TRUE, row.names = 1)
# select samples only from day 100
df <- df[grep('D100', rownames(df)), ]
# remove intergenic regions (if they're there)
df.noInter <- df[,!grepl('.B', colnames(df))]

# gene info dataframe
gene_path <- c("data/reference_assemblies_task2/reference_assemblies_task2_table/B.txt")
df.gene <- read.table(paste(gene_path, collapse = ''), sep = " ", header = TRUE, row.names = 1)
L <- sum(df.gene$Size)
df.gene$RelSize <- df.gene$Size / L
# sort df.gene according to column order in df
df.RelSize <- df.gene['RelSize']

df.merge <- merge(df.RelSize, t(df.noInter), by=0, all=TRUE)
rownames(df.merge) <- df.merge$Row.names
pmf <- df.merge$RelSize
df.merge <- subset(df.merge, select = -c(Row.names, RelSize) )
df.merge <- t(df.merge)
pop.muts <- rowSums(df.merge)
```


Get mean centroid distance using G-score matrix

```{r}
df.G <- make.G.matrix(df.merge, pmf)
df.G <- df.G[rowSums(df.G[,-1]) != 0,]
df.G <- df.G[, colSums(df.G != 0) > 0]
df.G.db <- vegdist(df.G, method = "bray", upper = TRUE, diag = TRUE)
df.G.groups <- substr(c(sapply(strsplit(rownames(df.G),"_"), `[`, 2)), 1, 3)
beta.disp <- betadisper(d = df.G.db, group = df.G.groups)
euc.mat <- get.euc.dist.2D(beta.disp)
euc.mean <- aggregate(eucs ~ treat.strain.names, euc.mat, FUN = function(x) mean(as.numeric(as.character(x))))
euc.var <- aggregate(eucs ~ treat.strain.names, euc.mat, FUN = function(x) var(as.numeric(as.character(x))))

rownames(euc.mean) <- euc.mean[,1]
euc.mean <- data.frame(euc.mean)
```




Get mean centroid distance values from random G-score matrices

```{r}
# call function with 1,000 iterations
df.null.euc <- sim.euc.dist(df.merge, pop.muts, pmf, df.G.groups, 1000)
# standardize mean centroid distances
df.null.euc.z <- scale(df.null.euc, center = TRUE, scale = TRUE)
df.null.euc.z.df <- data.frame(df.null.euc.z)
df.null.euc.z.u <- attr(df.null.euc.z, 'scaled:center')
df.null.euc.z.sd <- attr(df.null.euc.z, 'scaled:scal')

df.null.euc.z.u.mat <- data.frame(df.null.euc.z.u)
df.null.euc.z.sd.mat <- data.frame(df.null.euc.z.sd)
names(df.null.euc.z.u.mat)[1] <- "mean"
names(df.null.euc.z.sd.mat)[1] <- "sd"
euc.z.mat <- merge(df.null.euc.z.u.mat, df.null.euc.z.sd.mat, by=0, all=TRUE)
rownames(euc.z.mat) <- euc.mean[,1]

# get 95% CIs from permutation results
# 1,000 * 0.025 = 25
LCI <- c(sort(df.null.euc.z.df$L0B)[25], sort(df.null.euc.z.df$L0S)[25],
        sort(df.null.euc.z.df$L1B)[25], sort(df.null.euc.z.df$L1S)[25],
        sort(df.null.euc.z.df$L2B)[25], sort(df.null.euc.z.df$L2S)[25])
df.null.euc.z.u.mat["LCI"] <- LCI
UCI <- c(sort(df.null.euc.z.df$L0B)[1000-25], sort(df.null.euc.z.df$L0S)[1000-25],
        sort(df.null.euc.z.df$L1B)[1000-25], sort(df.null.euc.z.df$L1S)[1000-25],
        sort(df.null.euc.z.df$L2B)[1000-25], sort(df.null.euc.z.df$L2S)[1000-25])
df.null.euc.z.u.mat["UCI"] <- UCI

Bdisp.L0B <- (euc.mean['L0B', 'eucs'] - euc.z.mat['L0B', 'mean']) / euc.z.mat['L0B', 'sd']
Bdisp.L0S <- (euc.mean['L0S', 'eucs'] - euc.z.mat['L0S', 'mean']) / euc.z.mat['L0S', 'sd']
Bdisp.L1B <- (euc.mean['L1B', 'eucs'] - euc.z.mat['L1B', 'mean']) / euc.z.mat['L1B', 'sd']
Bdisp.L1S <- (euc.mean['L1S', 'eucs'] - euc.z.mat['L1S', 'mean']) / euc.z.mat['L1S', 'sd']
Bdisp.L2B <- (euc.mean['L2B', 'eucs'] - euc.z.mat['L2B', 'mean']) / euc.z.mat['L1B', 'sd']
Bdisp.L2S <- (euc.mean['L2S', 'eucs'] - euc.z.mat['L2S', 'mean']) / euc.z.mat['L1S', 'sd']
Bdisp <- c(Bdisp.L0B, Bdisp.L0S, Bdisp.L1B, Bdisp.L1S, Bdisp.L2B, Bdisp.L2S)
```


Plot data

Figure code based off of code written by Mario Muscarella for his relicDNA project. 

```{r}
#col2rgb("lightgrey")
col <- rgb(211,211,211,30,maxColorValue=255)
bg <- rgb(211,211,211,20,maxColorValue=255)

png(filename = paste(c("figs/beta-disper.png"), collapse = ''),
    width = 1200, height = 1200, res = 96*2)

par(mar = c(6, 5, 1, 1))

non.bp.rich <- plot(1, Bdisp[1], 
      ylim = c(-3.1, 3.1), xlim = c(0.5, 6.5), pch = 21, col = 'lightgrey', bg = 'lightgrey', lwd = 2,
      cex = 1.7, yaxt = "n", xaxt = "n", cex.lab = 2, cex.axis = 1.5,
      las = 1, ylab = "", xlab = "")
      box(lwd = 2)
points(2,  Bdisp[2], pch = 21, bg = "lightgrey", col = "lightgrey", lwd = 2, cex = 1.7)
points(3,  Bdisp[3], pch = 21, bg = "lightgrey", col = "lightgrey", lwd = 2, cex = 1.7)
points(4,  Bdisp[4], pch = 21, bg = "lightgrey", col = "lightgrey", lwd = 2, cex = 1.7)
points(5,  Bdisp[5], pch = 21, bg = "lightgrey", col = "lightgrey", lwd = 2, cex = 1.7)
points(6,  Bdisp[6], pch = 21, bg = "lightgrey", col = "lightgrey", lwd = 2, cex = 1.7)


points(1, df.null.euc.z.u.mat[1,1], pch = 21, col = "black", 
       bg = "NA", lwd = 2, cex = 2.5) 
points(2, df.null.euc.z.u.mat[2,1], pch = 21, col = "black", 
       bg = "NA", lwd = 2, cex = 2.5)  
points(3, df.null.euc.z.u.mat[3,1], pch = 21, col = "black", 
       bg = "NA", lwd = 2, cex = 2.5) 
points(4, df.null.euc.z.u.mat[4,1], pch = 21, col = "black", 
       bg = "NA", lwd = 2, cex = 2.5) 
points(5, df.null.euc.z.u.mat[5,1], pch = 21, col = "black", 
       bg = "NA", lwd = 2, cex = 2.5)
points(6, df.null.euc.z.u.mat[6,1], pch = 21, col = "black", 
       bg = "NA", lwd = 2, cex = 2.5) 
      
box(lwd = 2)

mtext(expression('Standardized mean centroid distance'), side = 2,
      outer = FALSE, cex = 1.5, line = 3.6, adj = 0.5)

# Major Axes
axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("-3.0", "-2.0", "-1.0", "0.0", "1.0", "2.0", "3.0"), at = c(-3, -2, -1, 0, 1, 2, 3))

axis(side = 4, lwd.ticks = 2, cex.axis = 1.5, las = 1,
     at=c(-3, -2, -1, 0, 1, 2, 3), labels = F, tck = -0.02)

axis(side = 1, lwd.ticks = 2, cex.axis = 0.9, las = 1,
     labels = c("B 1", "S 1", "B 10", "S 10", "B 100", "S 100"), at = c(1, 2, 3, 4, 5, 6))

axis(side = 3, lwd.ticks = 2, cex.axis = 1.5, las = 1,
     at = c(1, 2, 3, 4, 5, 6), labels = F, tck = -0.02)


arrows(x0 = c(1,2,3,4,5,6), y0 = df.null.euc.z.u.mat$mean, y1 = df.null.euc.z.u.mat$LCI, angle = 90, length = 0.1, lwd = 2)
arrows(x0 = c(1,2,3,4,5,6), y0 = df.null.euc.z.u.mat$mean, y1 = df.null.euc.z.u.mat$UCI, angle = 90, length=0.1, lwd = 2)

      
# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG(paste(c("figs/beta-disper.png"), collapse = ''))
grid.raster(img)


```

