# Fit growth curve to Gompertz equation. 
# This data is generated by taking manual readings from a spec
# Not from a plate reader

rm(list=ls())
getwd()
setwd('/Users/WRShoemaker/MURI/MURI_growth_curves/Acclimated_GC/')
getwd()

library(ggplot2)
library(xlsx)
library(reshape2)
library(RColorBrewer)
library(plyr)
library(Rmisc)

ODs <- read.xlsx("Acclimated_GC.xlsx", 1)
ODs_NA <- read.xlsx("../GC_dilution/GC_dilution_OD.xlsx", 2)

meltedNA <- melt(ODs_NA, id.vars="Time")
melted <- melt(ODs, id.vars="Time")

tgcNA <- summarySE(meltedNA, measurevar="value", groupvars=c("variable", "Time"))
tgc <- summarySE(melted, measurevar="value", groupvars=c("variable", "Time"))

pd <- position_dodge(0.1)
ggplot(tgc, aes(x=Time, y=value, colour=variable)) + 
  #geom_errorbar(aes(ymin=value-ci, ymax=value+ci), width=.1, position=pd) +
  geom_errorbar(aes(ymin=value-se, ymax=value+se), width=.1) +
  geom_line() +
  geom_point() +
  geom_step(data = tgcNA) +
  facet_wrap(~variable)


plot2 <- ggplot(NULL,  aes(x=factor(Time), y=value, colour=variable)) + 
  geom_line() +
  geom_point(data = tgc) +
  geom_step(data = tgcNA) + 
  geom_errorbar(aes(ymin=value-se, ymax=value+se), width=.1) +
  facet_wrap(~variable)

ggplot(tgc, aes(x = Time, y = value, colour = variable)) + 
  scale_color_discrete(name="Strain/Dilution",
                      breaks = c("Bacillus_10", "Bacillus_100", "Caulobacter_10", "Caulobacter_100",
                                 "Deinococcus_10", "Deinococcus_100", "Flavobacterium_10", 
                                 "Flavobacterium_100", "Janthinobacterium_10", "Janthinobacterium_100",
                                 "Micrococcus_10",  "Micrococcus_100"),
                      labels=c("Bacillus, 1:10", "Bacillus, 1:100", "Caulobacter, 1:10", 
                               "Caulobacter, 1:100", "Deinococcus, 1:10", "Deinococcus, 1:100", 
                               "Flavobacterium, 1:10", "Flavobacterium, 1:100", 
                               "Janthinobacterium, 1:10", "Janthinobacterium, 1:100",
                               "Micrococcus, 1:10", "Micrococcus, 1:100"))+
  geom_errorbar(aes(ymin=value-se, ymax=value+se), width=.1) +
  geom_point() + 
  geom_line(data = tgc, aes(y = value)) +  
  geom_line(data = tgcNA, aes(y = value)) +  
  facet_wrap(~variable) + 
  theme(strip.background = element_blank(),
        strip.text.x = element_blank()) +
  xlab("Time (hrs)") +
  ylab("OD 600") 

